[package]
name = "hackgt-timelapse"
version = "0.1.0"
authors = ["Ryan Petschek <petschekr@gmail.com>"]
edition = "2018"

[dependencies]
rust-s3 = "0.11.0"
rascam = "0.0.1"
pnet = "0.21.0"
crossbeam-channel = "0.3.8"
openssl-sys = "*"

[features]
vendored = ["openssl-sys/vendored"]
